spring:
  application:
    name: resilience4j
# port
server:
  port: 5000
# eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka

# resilience4j
resilience4j:
  retry:
    retry-aspect-order: 399 # 表示Retry的优先级
    backends:
      retryA:
        maxRetryAttempts: 5 # 重试次数
        waitDuration: 500 # 重试等待时间
        exponentialBackoffMultiplier: 1.1 # 间隔乘数
        retryExceptions:
          - java.lang.RuntimeException
  circuitbreaker:
    instances:
      cbA:
        ringBufferSizeInClosedState: 5 # 断路器关闭状态下，环形缓冲区的大小
        ringBufferSizeInHalfOpenState: 3 # 当断路器处于half open状态时，设置环形缓冲区的大小
        waitInterval: 5000 # 断路器从关闭状态切换到half open状态下，需要保持的时间间隔
        recordExceptions:
          - org.springframework.web.client.HttpServerErrorException
    circuit-breaker-aspect-order: 398